version: '2'
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 400
  method-complexity:
    enabled: false
  method-count:
    config:
      threshold: 20
  method-lines:
    enabled: false
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
plugins:
  eslint:
    enabled: true
    channel: 'eslint-7'
  markdownlint:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
  - '**/node_modules/'
  - 'dist/'
