name: 'streaming-slack-notify'

description: 'Send slack messages with attachments, auto username, branch and other actions'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'slack'
  color: 'blue'

env:
  SLACK_ACCESS_TOKEN:
    description: 'required'
    required: true

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true

  INTERNAL_STATUS_SUCCESS:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ success() }}
    required: true

  INTERNAL_STATUS_FAILURE:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ failure() }}
    required: true

  channel:
    description: 'Slack Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name. This is required to send the first Slack message. Subsequent github actions calls can omit this value for brevity.'
    required: false
  username:
    description: 'The slack bot user name'
    required: false
  icon_url:
    description: 'URL to an image to use as the icon for this message'
    required: false
  icon_emoji:
    description: 'Emoji to use as the icon for this message. Overrides "icon_url"'
    required: false

outputs:
  ts: # output will be available to future steps
    description: 'The message to output'
  channel: # output will be available to future steps
    description: 'The message to output'
