name: 'streaming-slack-notify'

description: 'The definitive Github Action for streaming workflow job status to Slack.'

runs:
  using: 'node12'
  main: 'packages/github-action/dist/index.js'

branding:
  icon: 'slack'
  color: 'blue'

inputs:
  ###
  ### User configurable options
  ###
  slack_app_token:
    description: 'The Slack API token'
    required: true
  channel:
    description: 'Slack Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name. This is required to send the first Slack message. Subsequent github actions calls can omit this value for brevity.'
    required: false
  username:
    description: 'The slack bot user name'
    required: false
  icon_url:
    description: 'URL to an image to use as the icon for this message'
    required: false
  icon_emoji:
    description: 'Emoji to use as the icon for this message. Overrides "icon_url"'
    required: false
  is_final_step:
    description: 'Flag that defines the last Slack notify step in your workflow. This step should be run with the "if: always()" condition to ensure that it always gets executed.'
    required: false

  ###
  ### Does not need to be specified from your action references
  ###
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true