name: 'streaming-slack-notify'

description: 'Send slack messages with attachments, auto username, branch and other actions'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'slack'
  color: 'blue'

inputs:
  ###
  ### User configurable options
  ###
  slack_access_token:
    description: 'required'
    required: true
  channel:
    description: 'Slack Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name. This is required to send the first Slack message. Subsequent github actions calls can omit this value for brevity.'
    required: false
  username:
    description: 'The slack bot user name'
    required: false
  icon_url:
    description: 'URL to an image to use as the icon for this message'
    required: false
  icon_emoji:
    description: 'Emoji to use as the icon for this message. Overrides "icon_url"'
    required: false
  is_final_step:
    description: 'Flag that defines the last Slack notify step in your workflow. This step should be run with the "if: always()" condition to ensure that it always gets executed.'
    required: false

outputs:

env:
  ###
  ### These do not need to be specified from your action references
  ###
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  JOB_STATUS:
    description: The status result as defined in the shell Job context. This is more accurate than the context currently running inside the worker node and thus we specify this as well.
    default: ${{ job.status }}
    required: true
