version: '3.7'

services:
  streaming-slack-notify:
    container_name: streaming-slack-notify
    image: node:12
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
