version: '3.7'

services:
  streaming-slack-notify:
    container_name: streaming-slack-notify
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
