name: Main

on:
  push:
    branches:
      - master
      - develop

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notify Init
        env:
          SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: techpivot/streaming-slack-notify@master
        with:
          channel: '#builds'

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Formatting
        run: sleep 4

      - name: Slack Notify
        env:
          SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: techpivot/streaming-slack-notify@master

      - name: Linting
        run: sleep 4

      - name: Slack Notify
        env:
          SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: techpivot/streaming-slack-notify@master

      - name: Building
        run: sleep 5

      - name: Slack Notify
        env:
          SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: techpivot/streaming-slack-notify@master

      - name: Packaging for deployment
        run: sleep 5

      - name: Slack Notify
        if: ${{ always() }}
        env:
          SLACK_ACCESS_TOKEN1: ${{ secrets.SLACK_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: techpivot/streaming-slack-notify@master

      - uses: technote-space/workflow-conclusion-action@v1
        if: always()
