name: Main

on:
  push:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Slack notification success
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: cemkiy/action-slacker@master
      with:
        channel: '#team-devops'
        color: '#00FFAA'
        username: 'github'
        icon_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        image_url: 'https://storage.googleapis.com/slack-images-cyclops/ci/It_Compiles_Ship_It.png'

    - name: Slack notification failure
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: cemkiy/action-slacker@master
      with:
        channel: '#team-devops'
        color: '#CC0000'
        username: 'github'
        icon_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        image_url: 'https://media.giphy.com/media/njYrp176NQsHS/giphy.gif'
