name: Main

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Slack notification success
        if: success()
        env:
          SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
        uses: techpivot/streaming-slack-notify@master
        with:
          channel: '#builds'
          color: '#00FFAA'
          icon_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          image_url: 'https://storage.googleapis.com/slack-images-cyclops/ci/It_Compiles_Ship_It.png'

      - name: Slack notification failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: techpivot/streaming-slack-notify@master
        with:
          channel: '#team-devops'
          color: '#CC0000'
          username: 'github'
          icon_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          image_url: 'https://media.giphy.com/media/njYrp176NQsHS/giphy.gif'
