name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  validate-and-build:
    name: Validate and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: yarn install

      - name: Formatting
        run: yarn format:check

      # - name: Linting
      #   run: yarn lint

      # - name: Building
      #   run: yarn build
